### ISSUE TITLE
giving the wrong item

### ISSUE THREAD

**Issue by RegressiaUK** [Ketheroth/Uncrafter#3]
When the mod shows one item when there is multiple recipes it  then returns a item from the other recipe item for the the recipe this as costed me hours of game play.

Please make a way to when it detects a recipe in the ui that is the item it replies not one from another recipe don't redo the item call, take the item in the slot.

This as happened on single player and servers. no errors given, this is on the first table the next table at the moment is out of my price range but I will update you with this later when I able to test this two.

MC: 1.16.5 
Mod: Uncrafter-1.16.5-0.4.0.jar

**Comment by Ketheroth** [comment]
This should be fixed in 1.16.5-1.0.0

fixed here : a568fdd0a3461afcdef51f0a1a1c85d65b571b4d
